[project]
name = "opis"
version = "1.0.0"
description = "OPIS: Orbital Planetary Interactive Simulator—A project for the ASTRO 100/G Lab"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=8.0.1",
    "fastapi[standard]>=0.141.1",
    "rebound==5.2.2",
    "tzdata>=2026.3",
]
